version: '3.1'
 
services:
 
  wordpress:
    image: wordpress:5.5-php7.2-apache
    ports:
      - 9080:80
    environment:
      WORDPRESS_DB_HOST: mysql
      WORDPRESS_DB_USER: root
      WORDPRESS_DB_PASSWORD: root
      WORDPRESS_DB_NAME: wp_yummies
    volumes:
      - "/home/debian/taquewp:/var/www/html"
    links:
      - mysql:mysql
 
 
  mysql:
    image: mysql:8.0.21
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_DATABASE: wp_yummies
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - "/home/debian/taquedb:/var/lib/mysql"
